packages:
  - 'apps/*'
  - 'packages/*'

# Configurações específicas do workspace
catalog:
  # Dependências compartilhadas
  typescript: ^5.3.3
  '@types/node': ^20.10.0
  zod: ^3.22.4
  
  # Framework e runtime
  express: ^4.18.2
  '@types/express': ^4.17.21
  fastify: ^4.24.3
  
  # Validação e utilitários
  joi: ^17.11.0
  lodash: ^4.17.21
  '@types/lodash': ^4.14.202
  
  # Testes
  vitest: ^1.1.0
  '@vitest/ui': ^1.1.0
  
  # Build e desenvolvimento
  tsup: ^8.0.1
  tsx: ^4.6.2
  nodemon: ^3.0.2
