export const GENERATE_PROPOSAL_ANCHOR_ID: "command-generate-proposal";
export default ConversationHeader;
export function ConversationHeader({ ticket, onRegisterResult, onRegisterCallResult, onAssign, onSendTemplate, onCreateNextStep, onGenerateProposal, onScheduleFollowUp, onSendSMS, onAttachFile, onEditContact, typingAgents, isRegisteringResult, renderSummary, onContactFieldSave, onDealFieldSave, nextStepValue, onNextStepSave, onFocusComposer, composerHeight, aiMode, aiConfidence, aiModeChangeDisabled, onTakeOver, onGiveBackToAi, onAiModeChange, onCreateNote, timeline, aiAssistant, components, detailsOpen, onRequestDetails, nextStepEditorRef: externalNextStepEditorRef, primaryActionOverride, }: {
    ticket: any;
    onRegisterResult: any;
    onRegisterCallResult: any;
    onAssign: any;
    onSendTemplate: any;
    onCreateNextStep: any;
    onGenerateProposal: any;
    onScheduleFollowUp: any;
    onSendSMS: any;
    onAttachFile: any;
    onEditContact: any;
    typingAgents?: never[] | undefined;
    isRegisteringResult?: boolean | undefined;
    renderSummary: any;
    onContactFieldSave: any;
    onDealFieldSave: any;
    nextStepValue: any;
    onNextStepSave: any;
    onFocusComposer: any;
    composerHeight: any;
    aiMode?: string | undefined;
    aiConfidence?: null | undefined;
    aiModeChangeDisabled?: boolean | undefined;
    onTakeOver: any;
    onGiveBackToAi: any;
    onAiModeChange: any;
    onCreateNote: any;
    timeline?: never[] | undefined;
    aiAssistant: any;
    components: any;
    detailsOpen?: boolean | undefined;
    onRequestDetails: any;
    nextStepEditorRef: any;
    primaryActionOverride?: null | undefined;
}): import("react/jsx-runtime").JSX.Element;
import { PrimaryActionButton } from './PrimaryActionBanner.jsx';
export { PrimaryActionButton };
