import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card.jsx';
import { Badge } from '@/components/ui/badge.jsx';
import { Separator } from '@/components/ui/separator.jsx';
const ContactSummary = ({ contact }) => {
    if (!contact) {
        return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Resumo" }) }), _jsx(CardContent, { className: "text-sm text-muted-foreground", children: "Selecione um contato para visualizar o resumo." })] }));
    }
    const tags = Array.isArray(contact.tags) ? contact.tags : [];
    const customFields = contact.customFields && typeof contact.customFields === 'object' ? contact.customFields : {};
    return (_jsxs("div", { className: "grid gap-4 md:grid-cols-2", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Informa\u00E7\u00F5es principais" }) }), _jsxs(CardContent, { className: "space-y-3 text-sm", children: [_jsxs("div", { children: [_jsx("span", { className: "block text-xs font-medium uppercase text-muted-foreground", children: "Nome" }), _jsx("span", { className: "text-base font-semibold", children: contact.name ?? 'Contato sem nome' })] }), _jsxs("div", { children: [_jsx("span", { className: "block text-xs font-medium uppercase text-muted-foreground", children: "Telefone" }), _jsx("span", { children: contact.phone ?? '—' })] }), _jsxs("div", { children: [_jsx("span", { className: "block text-xs font-medium uppercase text-muted-foreground", children: "E-mail" }), _jsx("span", { children: contact.email ?? '—' })] }), _jsxs("div", { children: [_jsx("span", { className: "block text-xs font-medium uppercase text-muted-foreground", children: "Documento" }), _jsx("span", { children: contact.document ?? '—' })] }), _jsxs("div", { children: [_jsx("span", { className: "block text-xs font-medium uppercase text-muted-foreground", children: "Tags" }), _jsxs("div", { className: "mt-2 flex flex-wrap items-center gap-2", children: [tags.length === 0 ? _jsx(Badge, { variant: "outline", children: "Sem tags" }) : null, tags.map((tag) => (_jsx(Badge, { variant: "secondary", children: tag }, tag)))] })] })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Campos personalizados" }) }), _jsx(CardContent, { children: Object.keys(customFields).length === 0 ? (_jsx("p", { className: "text-sm text-muted-foreground", children: "Nenhum campo personalizado preenchido." })) : (_jsx("dl", { className: "space-y-3 text-sm", children: Object.entries(customFields).map(([key, value]) => (_jsxs("div", { children: [_jsx("dt", { className: "text-xs font-medium uppercase text-muted-foreground", children: key }), _jsx("dd", { children: String(value) }), _jsx(Separator, { className: "my-2" })] }, key))) })) })] })] }));
};
export default ContactSummary;
