export {
  normalizeQueryValue,
  normalizeBooleanValue,
  resolveRequestTenantId,
  resolveRequestActorId,
  resolveDefaultInstanceId,
  looksLikeWhatsAppJid,
  readInstanceIdParam,
  readBrokerErrorStatus,
  hasErrorName,
  isBrokerAlreadyDisconnectedError,
  isBrokerMissingInstanceError,
  INVALID_INSTANCE_ID_MESSAGE,
  instanceIdParamValidator,
  createWhatsAppInstanceSchema,
  createWhatsAppInstance,
  executeSideEffects,
  WhatsAppInstanceAlreadyExistsError,
  WhatsAppInstanceInvalidPayloadError,
  respondWhatsAppStorageUnavailable,
  respondWhatsAppNotConfigured,
  handleWhatsAppIntegrationError,
  describeErrorForLog,
  logWhatsAppStorageError,
  respondWhatsAppBrokerFailure,
  respondLegacyEndpointGone,
  collectInstancesForTenant,
  buildInstanceStatusPayload,
  fetchStatusWithBrokerQr,
  normalizeInstanceStatusResponse,
  normalizeQr,
  extractQrImageBuffer,
  disconnectStoredInstance,
  deleteStoredInstance,
  resolveInstanceOperationContext,
  serializeStoredInstance,
  normalizeStatusCountsData,
  normalizeRateUsageData,
  collectNumericFromSources,
  syncInstancesFromBroker,
  archiveInstanceSnapshot,
  scheduleWhatsAppDisconnectRetry,
  clearWhatsAppDisconnectRetry,
  removeCachedSnapshot,
  clearInstanceArchive,
} from './service';

export type { NormalizedInstance, StoredInstance, InstanceOperationContext } from './service';
