import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '@/components/ui/badge.jsx';
import { Button } from '@/components/ui/button.jsx';
import { Skeleton } from '@/components/ui/skeleton.jsx';
import InstanceSummaryCard from './InstanceSummaryCard.jsx';
const InstanceGrid = ({ instancesReady, filteredInstances, statusCodeMeta, isBusy, isAuthenticated, deletingInstanceId, hasRenderableInstances, hasHiddenInstances, zeroInstances, onShowAll, onCreateInstance, createInstanceDisabled = false, createInstanceWarning = null, onSelectInstance, onViewQr, onRequestDelete, onOpenStatusDrawer, onOpenHealthDrawer, onRenameInstance, onViewLogs, highQueue, allDisconnected, onClearFilters, }) => {
    if (!instancesReady) {
        return (_jsx("div", { className: "grid gap-4", style: { gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))' }, children: Array.from({ length: 4 }).map((_, index) => (_jsxs("div", { className: "rounded-2xl border border-slate-800/60 bg-slate-950/60 p-4 shadow-inner", children: [_jsx(Skeleton, { className: "h-5 w-3/4" }), _jsx(Skeleton, { className: "mt-2 h-4 w-1/2" }), _jsxs("div", { className: "mt-4 grid grid-cols-3 gap-2", children: [_jsx(Skeleton, { className: "h-12 w-full" }), _jsx(Skeleton, { className: "h-12 w-full" }), _jsx(Skeleton, { className: "h-12 w-full" })] }), _jsx(Skeleton, { className: "mt-4 h-16 w-full" }), _jsx(Skeleton, { className: "mt-4 h-10 w-full" })] }, index))) }));
    }
    return (_jsxs("div", { className: "space-y-4", children: [highQueue || allDisconnected ? (_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [highQueue ? (_jsx(Badge, { className: "rounded-full border border-indigo-400/40 bg-indigo-500/10 px-3 py-1 text-[0.65rem] text-indigo-100", children: "Fila elevada nas \u00FAltimas 2h" })) : null, allDisconnected ? (_jsx(Badge, { className: "rounded-full border border-amber-400/40 bg-amber-500/10 px-3 py-1 text-[0.65rem] text-amber-100", children: "Nenhum canal conectado" })) : null] })) : null, hasRenderableInstances ? (_jsx("div", { className: "grid gap-4", style: { gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))' }, children: filteredInstances.map((viewModel) => (_jsx(InstanceSummaryCard, { viewModel: viewModel, statusCodeMeta: statusCodeMeta, isBusy: isBusy, isAuthenticated: isAuthenticated, deletingInstanceId: deletingInstanceId, onSelectInstance: onSelectInstance, onViewQr: onViewQr, onRequestDelete: onRequestDelete, onOpenStatusDrawer: onOpenStatusDrawer, onOpenHealthDrawer: onOpenHealthDrawer, onRenameInstance: onRenameInstance, onViewLogs: (instance) => onViewLogs?.(instance.instance ?? instance) }, viewModel.key))) })) : hasHiddenInstances ? (_jsxs("div", { className: "rounded-2xl border border-slate-800/60 bg-slate-950/60 p-6 text-center text-sm text-muted-foreground", children: [_jsx("p", { children: "Nenhuma inst\u00E2ncia conectada no momento. Ajuste os filtros para gerenciar sess\u00F5es desconectadas." }), _jsx(Button, { size: "sm", className: "mt-4", onClick: onShowAll, disabled: isBusy, children: "Mostrar todas" })] })) : zeroInstances ? (_jsxs("div", { className: "rounded-2xl border border-slate-800/60 bg-slate-950/60 p-8 text-center", children: [_jsx("h3", { className: "text-lg font-semibold text-foreground", children: "Crie sua primeira inst\u00E2ncia" }), _jsx("p", { className: "mt-2 text-sm text-muted-foreground", children: "Configure um canal do WhatsApp para come\u00E7ar a operar com o Lead Engine." }), _jsx(Button, { size: "sm", className: "mt-4", onClick: onCreateInstance, disabled: isBusy || createInstanceDisabled, children: "Nova inst\u00E2ncia" }), createInstanceWarning ? (_jsx("p", { className: "mt-2 text-xs text-amber-200", children: createInstanceWarning })) : null] })) : (_jsxs("div", { className: "rounded-2xl border border-slate-800/60 bg-slate-950/60 p-6 text-center text-sm text-muted-foreground", children: [_jsx("p", { children: "Nenhuma inst\u00E2ncia encontrada para os filtros aplicados." }), _jsx(Button, { size: "sm", className: "mt-4", variant: "outline", onClick: onClearFilters, children: "Limpar filtros" })] }))] }));
};
export default InstanceGrid;
