CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`company` varchar(255) NOT NULL,
	`role` varchar(255) NOT NULL,
	`baseSize` varchar(50) NOT NULL,
	`interestedInFunding` boolean NOT NULL,
	`message` text NOT NULL,
	`utmSource` varchar(255),
	`utmMedium` varchar(255),
	`utmCampaign` varchar(255),
	`referrer` text,
	`pageVariant` varchar(100),
	`device` varchar(50),
	`country` varchar(100),
	`state` varchar(100),
	`score` int NOT NULL DEFAULT 0,
	`tier` enum('A','B','C') NOT NULL DEFAULT 'C',
	`status` enum('new','contacted','qualified','converted','lost') NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
