import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '@/components/ui/badge.jsx';
import { Button } from '@/components/ui/button.jsx';
import { Input } from '@/components/ui/input.jsx';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from '@/components/ui/select.jsx';
import { Search } from 'lucide-react';
const InstanceFiltersBar = ({ searchTerm, onSearchChange, statusFilter, onStatusFilterChange, statusOptions, healthFilter, onHealthFilterChange, healthOptions, providerFilter, onProviderFilterChange, providerOptions, sortBy, onSortByChange, sortOptions, activeInstances, totalInstances, filtersApplied, onClearFilters, }) => {
    const filtersActive = filtersApplied > 0;
    return (_jsxs("div", { className: "flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between", children: [_jsxs("div", { className: "flex flex-1 flex-wrap items-center gap-3", children: [_jsxs("div", { className: "relative min-w-[220px] flex-1", children: [_jsx(Search, { className: "pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" }), _jsx(Input, { value: searchTerm, onChange: (event) => onSearchChange(event.target.value), placeholder: "Buscar inst\u00E2ncia por nome ou telefone", className: "pl-9" })] }), _jsxs(Select, { value: statusFilter, onValueChange: onStatusFilterChange, children: [_jsx(SelectTrigger, { className: "w-[180px]", children: _jsx(SelectValue, { placeholder: "Status" }) }), _jsx(SelectContent, { children: statusOptions.map((option) => (_jsx(SelectItem, { value: option.value, children: option.label }, option.value))) })] }), _jsxs(Select, { value: healthFilter, onValueChange: onHealthFilterChange, children: [_jsx(SelectTrigger, { className: "w-[180px]", children: _jsx(SelectValue, { placeholder: "Sa\u00FAde" }) }), _jsx(SelectContent, { children: healthOptions.map((option) => (_jsx(SelectItem, { value: option.value, children: option.label }, option.value))) })] }), _jsxs(Select, { value: providerFilter, onValueChange: onProviderFilterChange, children: [_jsx(SelectTrigger, { className: "w-[180px]", children: _jsx(SelectValue, { placeholder: "Provedor" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "all", children: "Todos os provedores" }), providerOptions.map((provider) => (_jsx(SelectItem, { value: provider, children: provider }, provider)))] })] })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs(Select, { value: sortBy, onValueChange: onSortByChange, children: [_jsx(SelectTrigger, { className: "w-[220px]", children: _jsx(SelectValue, { placeholder: "Ordenar por" }) }), _jsx(SelectContent, { children: sortOptions.map((option) => (_jsx(SelectItem, { value: option.value, children: option.label }, option.value))) })] }), _jsx(Badge, { variant: filtersActive ? 'secondary' : 'outline', className: "px-3 py-1 text-[0.65rem] uppercase tracking-wide text-muted-foreground", children: filtersActive ? `${filtersApplied} filtro${filtersApplied > 1 ? 's' : ''} ativos` : 'Nenhum filtro ativo' }), _jsx(Button, { type: "button", size: "sm", variant: "ghost", onClick: onClearFilters, disabled: !filtersActive, className: "rounded-full text-xs", children: "Limpar filtros" }), _jsxs(Badge, { variant: "outline", className: "px-3 py-1 text-[0.65rem] uppercase tracking-wide text-muted-foreground", children: [activeInstances, " de ", totalInstances, " exibidas"] })] })] }));
};
export default InstanceFiltersBar;
