export default InstancesPanel;
declare function InstancesPanel({ surfaceStyles: _surfaceStyles, selectedInstance, selectedInstanceStatusInfo, selectedInstancePhone, instancesReady, hasHiddenInstances, hasRenderableInstances, instanceViewModels, showFilterNotice, instancesCountLabel, errorState, isBusy, isAuthenticated, loadingInstances, copy, localStatus, onMarkConnected, onRefresh, onCreateInstance, onShowAll, onRetry, onSelectInstance, onViewQr, onRequestDelete, deletingInstanceId, statusCodeMeta, onViewLogs, onRenameInstance, qrStatusMessage, countdownMessage, canContinue, canCreateCampaigns, createInstanceDisabled, createInstanceWarning, }: {
    surfaceStyles: any;
    selectedInstance: any;
    selectedInstanceStatusInfo: any;
    selectedInstancePhone: any;
    instancesReady: any;
    hasHiddenInstances: any;
    hasRenderableInstances: any;
    instanceViewModels: any;
    showFilterNotice: any;
    instancesCountLabel: any;
    errorState: any;
    isBusy: any;
    isAuthenticated: any;
    loadingInstances: any;
    copy: any;
    localStatus: any;
    onMarkConnected: any;
    onRefresh: any;
    onCreateInstance: any;
    onShowAll: any;
    onRetry: any;
    onSelectInstance: any;
    onViewQr: any;
    onRequestDelete: any;
    deletingInstanceId: any;
    statusCodeMeta: any;
    onViewLogs: any;
    onRenameInstance: any;
    qrStatusMessage: any;
    countdownMessage: any;
    canContinue: any;
    canCreateCampaigns: any;
    createInstanceDisabled?: boolean | undefined;
    createInstanceWarning?: null | undefined;
}): import("react/jsx-runtime").JSX.Element;
